import initAccordion from './modules/accordion.js';
import initAnimationScroll from './modules/animacao-scroll.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initModal from './modules/modal.js';
import scrollToSection from './modules/scroll-suave.js';
import tabMenuActive from './modules/tab-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimais from './modules/fetch-animais.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

initAccordion();
initAnimationScroll();
initDropDownMenu();
initModal();
scrollToSection();
tabMenuActive();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
